-- Development seed data for lean-saas template

-- Note: This seed data is for development only
-- Do not run this in production

-- Create test users first (these will be created through auth, but we need profiles)
-- User IDs would typically be generated by auth.users, using placeholder UUIDs here

-- Insert test profiles
INSERT INTO public.profiles (id, email, full_name, plan_type, onboarded, created_at, updated_at) VALUES
    ('11111111-1111-1111-1111-111111111111', 'john@example.com', 'John Doe', 'pro', true, NOW(), NOW()),
    ('22222222-2222-2222-2222-222222222222', 'jane@example.com', 'Jane Smith', 'free', true, NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333333', 'bob@example.com', 'Bob Johnson', 'enterprise', true, NOW(), NOW()),
    ('44444444-4444-4444-4444-444444444444', 'alice@example.com', 'Alice Brown', 'free', false, NOW(), NOW()),
    ('55555555-5555-5555-5555-555555555555', 'charlie@example.com', 'Charlie Wilson', 'pro', true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Insert test organizations
INSERT INTO public.organizations (id, name, slug, plan_type, owner_id, created_at, updated_at) VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Acme Corporation', 'acme-corp', 'enterprise', '11111111-1111-1111-1111-111111111111', NOW(), NOW()),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Tech Startup Inc', 'tech-startup', 'pro', '22222222-2222-2222-2222-222222222222', NOW(), NOW()),
    ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'Design Agency', 'design-agency', 'pro', '33333333-3333-3333-3333-333333333333', NOW(), NOW()),
    ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'Solo Consulting', 'solo-consulting', 'free', '44444444-4444-4444-4444-444444444444', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Insert organization members
INSERT INTO public.organization_members (organization_id, user_id, role, invited_by, joined_at) VALUES
    -- Acme Corporation members
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '11111111-1111-1111-1111-111111111111', 'owner', NULL, NOW()),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '22222222-2222-2222-2222-222222222222', 'admin', '11111111-1111-1111-1111-111111111111', NOW()),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', '55555555-5555-5555-5555-555555555555', 'member', '11111111-1111-1111-1111-111111111111', NOW()),
    
    -- Tech Startup Inc members
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '22222222-2222-2222-2222-222222222222', 'owner', NULL, NOW()),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', '33333333-3333-3333-3333-333333333333', 'member', '22222222-2222-2222-2222-222222222222', NOW()),
    
    -- Design Agency members
    ('cccccccc-cccc-cccc-cccc-cccccccccccc', '33333333-3333-3333-3333-333333333333', 'owner', NULL, NOW()),
    ('cccccccc-cccc-cccc-cccc-cccccccccccc', '44444444-4444-4444-4444-444444444444', 'member', '33333333-3333-3333-3333-333333333333', NOW()),
    
    -- Solo Consulting (single member)
    ('dddddddd-dddd-dddd-dddd-dddddddddddd', '44444444-4444-4444-4444-444444444444', 'owner', NULL, NOW())
ON CONFLICT (organization_id, user_id) DO NOTHING;

-- Insert sample projects
INSERT INTO public.projects (id, organization_id, name, description, status, created_by, created_at, updated_at) VALUES
    -- Acme Corporation projects
    ('project-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Customer Portal Redesign', 'Modernizing our customer portal with React and TypeScript', 'active', '11111111-1111-1111-1111-111111111111', NOW(), NOW()),
    ('project-2222-2222-2222-222222222222', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Mobile App Development', 'Building a mobile app for our platform using React Native', 'active', '22222222-2222-2222-2222-222222222222', NOW(), NOW()),
    ('project-3333-3333-3333-333333333333', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Legacy System Migration', 'Migrating from old PHP system to modern stack', 'archived', '11111111-1111-1111-1111-111111111111', NOW() - INTERVAL '30 days', NOW()),
    
    -- Tech Startup Inc projects
    ('project-4444-4444-4444-444444444444', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'MVP Development', 'Building the minimum viable product for our SaaS platform', 'active', '22222222-2222-2222-2222-222222222222', NOW(), NOW()),
    ('project-5555-5555-5555-555555555555', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'User Analytics Dashboard', 'Creating comprehensive analytics for user behavior', 'active', '33333333-3333-3333-3333-333333333333', NOW(), NOW()),
    
    -- Design Agency projects
    ('project-6666-6666-6666-666666666666', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 'Brand Identity Redesign', 'Complete rebrand for major client', 'active', '33333333-3333-3333-3333-333333333333', NOW(), NOW()),
    ('project-7777-7777-7777-777777777777', 'cccccccc-cccc-cccc-cccc-cccccccccccc', 'E-commerce Website', 'Custom e-commerce solution for fashion brand', 'active', '44444444-4444-4444-4444-444444444444', NOW(), NOW()),
    
    -- Solo Consulting projects
    ('project-8888-8888-8888-888888888888', 'dddddddd-dddd-dddd-dddd-dddddddddddd', 'Freelance Project Management', 'Personal project tracking and time management', 'active', '44444444-4444-4444-4444-444444444444', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Insert sample subscription data (for testing billing)
INSERT INTO public.subscriptions (id, organization_id, user_id, stripe_subscription_id, stripe_price_id, status, current_period_start, current_period_end, cancel_at_period_end, created_at, updated_at) VALUES
    -- Organization subscriptions
    ('sub-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', NULL, 'sub_test_acme_enterprise', 'price_test_enterprise', 'active', NOW() - INTERVAL '15 days', NOW() + INTERVAL '15 days', false, NOW() - INTERVAL '15 days', NOW()),
    ('sub-2222-2222-2222-222222222222', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', NULL, 'sub_test_startup_pro', 'price_test_pro', 'active', NOW() - INTERVAL '10 days', NOW() + INTERVAL '20 days', false, NOW() - INTERVAL '10 days', NOW()),
    ('sub-3333-3333-3333-333333333333', 'cccccccc-cccc-cccc-cccc-cccccccccccc', NULL, 'sub_test_design_pro', 'price_test_pro', 'active', NOW() - INTERVAL '5 days', NOW() + INTERVAL '25 days', false, NOW() - INTERVAL '5 days', NOW()),
    
    -- Individual user subscriptions
    ('sub-4444-4444-4444-444444444444', NULL, '11111111-1111-1111-1111-111111111111', 'sub_test_john_pro', 'price_test_pro', 'active', NOW() - INTERVAL '20 days', NOW() + INTERVAL '10 days', false, NOW() - INTERVAL '20 days', NOW()),
    ('sub-5555-5555-5555-555555555555', NULL, '55555555-5555-5555-5555-555555555555', 'sub_test_charlie_pro', 'price_test_pro', 'trialing', NOW(), NOW() + INTERVAL '7 days', false, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Add comments for understanding
COMMENT ON TABLE public.profiles IS 'User profiles with plan information';
COMMENT ON TABLE public.organizations IS 'Organizations/teams for multi-tenant functionality';
COMMENT ON TABLE public.organization_members IS 'Membership relationships between users and organizations';
COMMENT ON TABLE public.subscriptions IS 'Stripe subscription tracking for billing';
COMMENT ON TABLE public.projects IS 'Main business entities - projects managed by organizations';

-- Create indexes for better performance with RLS policies
CREATE INDEX IF NOT EXISTS idx_organization_members_user_id_org_id ON public.organization_members(user_id, organization_id);
CREATE INDEX IF NOT EXISTS idx_organization_members_org_id_role ON public.organization_members(organization_id, role);
CREATE INDEX IF NOT EXISTS idx_projects_org_id_status ON public.projects(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_projects_created_by ON public.projects(created_by);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_org_id ON public.subscriptions(organization_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_id ON public.subscriptions(stripe_subscription_id);

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO authenticated, anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;